repos:
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        language_version: python3.9
        args: [--skip-string-normalization]
        additional_dependencies: ['pip>=21.3.1']

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--profile=black]
        additional_dependencies: ['pip>=21.3.1']

default_language_version:
    python: python3.9

default_install_hook_types: [pre-commit, pre-push]

ci:
    autofix_commit_msg: 'style: auto fixes from pre-commit hooks'
    autoupdate_commit_msg: 'ci: pre-commit autoupdate'
    skip: [black, isort]

repos_trust_cert: true 