name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'frontend/**'
    branches: [ main ]

env:
  PYTHON_VERSION: "3.9"

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        cd frontend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black isort
    
    - name: Check formatting with Black
      run: |
        cd frontend
        python -m black . --check
    
    - name: Check imports with isort
      run: |
        cd frontend
        python -m isort . --check-only --profile black

  deploy:
    needs: lint
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        cd frontend
        pip install streamlit

    # Note: Manual deployment instructions
    # 1. Go to https://share.streamlit.io/
    # 2. Deploy from GitHub repository
    # 3. Set main file path to: frontend/streamlit_app.py
    # 4. Add the following secrets in Streamlit Cloud:
    #    - streamlit_token
    #    - backend_api_key
    #    - backend_api_url