name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'frontend/**'
    branches: [ main ]

env:
  STREAMLIT_APP_NAME: "100x-discovery"
  PYTHON_VERSION: "3.9"

permissions:
  contents: read
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        cd frontend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black isort
    
    - name: Check formatting with Black
      run: |
        cd frontend
        python -m black . --check
    
    - name: Check imports with isort
      run: |
        cd frontend
        python -m isort . --check-only --profile black
  
  deploy:
    needs: lint
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://share.streamlit.io
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Create .streamlit directory
      run: mkdir -p frontend/.streamlit
    
    - name: Create secrets.toml
      env:
        STREAMLIT_TOKEN: ${{ secrets.STREAMLIT_TOKEN }}
        BACKEND_API_URL: ${{ secrets.BACKEND_API_URL }}
        BACKEND_API_KEY: ${{ secrets.BACKEND_API_KEY }}
      run: |
        cat << EOF > frontend/.streamlit/secrets.toml
        [general]
        STREAMLIT_TOKEN = "${STREAMLIT_TOKEN}"
        BACKEND_API_URL = "${BACKEND_API_URL}"
        BACKEND_API_KEY = "${BACKEND_API_KEY}"
        EOF
    
    - name: Deploy to Streamlit Cloud
      env:
        STREAMLIT_TOKEN: ${{ secrets.STREAMLIT_TOKEN }}
      uses: streamlit/cloud-deploy-action@v1
      with:
        app-name: ${{ env.STREAMLIT_APP_NAME }}
        streamlit-token: ${STREAMLIT_TOKEN}
        root-path: "./frontend"