name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
    branches: [ main ]
  pull_request:
    paths:
      - 'frontend/**'
    branches: [ main ]

env:
  PYTHON_VERSION: "3.9"

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        cd frontend
        python -m pip install --upgrade pip
        # Add retry mechanism for dependency installation
        for i in 1 2 3; do
          echo "Attempt $i to install dependencies..."
          pip install -r requirements.txt && break || { 
            if [ $i -lt 3 ]; then
              echo "Dependency installation failed, retrying in 10 seconds..."
              sleep 10
            else
              echo "Dependency installation failed after 3 attempts"
              exit 1
            fi
          }
        done
        # Install linting tools separately with retry
        for i in 1 2 3; do
          echo "Attempt $i to install linting tools..."
          pip install black==23.11.0 isort==5.12.0 && break || {
            if [ $i -lt 3 ]; then
              echo "Tools installation failed, retrying in 10 seconds..."
              sleep 10
            else
              echo "Tools installation failed after 3 attempts"
              exit 1
            fi
          }
        done
    
    - name: Check formatting with Black
      run: |
        cd frontend
        # Use the --skip-string-normalization flag to match the pyproject.toml configuration
        python -m black . --check --skip-string-normalization
    
    - name: Check imports with isort
      run: |
        cd frontend
        python -m isort . --check-only --profile black

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        cd frontend
        python -m pip install --upgrade pip
        # Add retry mechanism for dependency installation
        for i in 1 2 3; do
          echo "Attempt $i to install dependencies..."
          pip install -r requirements.txt && break || { 
            if [ $i -lt 3 ]; then
              echo "Dependency installation failed, retrying in 10 seconds..."
              sleep 10
            else
              echo "Dependency installation failed after 3 attempts"
              exit 1
            fi
          }
        done
        # Install test tools separately with retry
        for i in 1 2 3; do
          echo "Attempt $i to install test tools..."
          pip install pytest pytest-cov && break || {
            if [ $i -lt 3 ]; then
              echo "Test tools installation failed, retrying in 10 seconds..."
              sleep 10
            else
              echo "Test tools installation failed after 3 attempts"
              exit 1
            fi
          }
        done
    
    - name: Create test environment file
      run: |
        cd frontend
        echo "STREAMLIT_TOKEN=test_token" > .env
        echo "BACKEND_API_KEY=test_key" >> .env
        echo "BACKEND_API_URL=http://localhost:8000" >> .env
    
    - name: Run tests
      run: |
        cd frontend
        python -m pytest tests/test_basic.py -v
      env:
        PYTHONPATH: ${{ github.workspace }}/frontend

  deploy:
    needs: [test]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        cd frontend
        python -m pip install --upgrade pip
        # Add retry mechanism for dependency installation
        for i in 1 2 3; do
          echo "Attempt $i to install dependencies..."
          pip install -r requirements.txt && break || { 
            if [ $i -lt 3 ]; then
              echo "Dependency installation failed, retrying in 10 seconds..."
              sleep 10
            else
              echo "Dependency installation failed after 3 attempts"
              exit 1
            fi
          }
        done

    - name: Create .streamlit directory
      run: mkdir -p frontend/.streamlit

    - name: Create secrets.toml
      run: |
        echo "[general]" > frontend/.streamlit/secrets.toml
        echo "STREAMLIT_TOKEN = \"${{ secrets.STREAMLIT_TOKEN || 'dummy_token' }}\"" >> frontend/.streamlit/secrets.toml
        echo "BACKEND_API_KEY = \"${{ secrets.BACKEND_API_KEY || 'dummy_key' }}\"" >> frontend/.streamlit/secrets.toml
        echo "BACKEND_API_URL = \"${{ secrets.BACKEND_API_URL || 'http://localhost:8000' }}\"" >> frontend/.streamlit/secrets.toml

    - name: Deploy to Streamlit Cloud
      run: |
        # Install Streamlit CLI if needed
        pip install streamlit
        
        # For now, this is a placeholder as Streamlit Cloud uses GitHub integration
        echo "Note: Streamlit Cloud automatically deploys from GitHub. Please ensure GitHub integration is set up in Streamlit Cloud."
        echo "Deployment complete!" 